kind: pipeline
type: docker
name: default
steps:
- name: greeting
  image: alpine
  commands:
  - echo hello world
  - echo update to trigger build
  when:
    event:
    - pull_request
    instance:
    - drone-pr.rancher.io
node:
  environment: test
